import { SortOrder } from "../../util/SortOrder";

export type TestEthicOrderByInput = {
  amendmentNumber?: SortOrder;
  appCreatedBy?: SortOrder;
  appModifiedBy?: SortOrder;
  approvalDate?: SortOrder;
  approvalExpiryDate?: SortOrder;
  approvalReference?: SortOrder;
  approvalRequirementBy?: SortOrder;
  approvalValidFor?: SortOrder;
  chairsAction?: SortOrder;
  created?: SortOrder;
  createdAt?: SortOrder;
  createdBy?: SortOrder;
  decisionNotificationWorkflow_2?: SortOrder;
  doNotUseApprovalExpiryDate?: SortOrder;
  doNotUsePiName?: SortOrder;
  doNotUsePreviousStatus?: SortOrder;
  emailComments?: SortOrder;
  enterpriseProject?: SortOrder;
  ethicsPanelView?: SortOrder;
  firstApproved?: SortOrder;
  healthOfSport?: SortOrder;
  id?: SortOrder;
  institution?: SortOrder;
  itemType?: SortOrder;
  meetingDate?: SortOrder;
  migrateFlow?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  newApplicationRequest?: SortOrder;
  notes?: SortOrder;
  path?: SortOrder;
  principalInvestigator?: SortOrder;
  projectStatus?: SortOrder;
  projectSupervisor?: SortOrder;
  projectTitle?: SortOrder;
  projectType?: SortOrder;
  requiresChairsAction?: SortOrder;
  reSubmission?: SortOrder;
  specialConsideration?: SortOrder;
  testEmailToPrincipleInvestigator?: SortOrder;
  updatedAt?: SortOrder;
};
