export type TestEthic = {
  amendmentNumber: number | null;
  appCreatedBy: number | null;
  appModifiedBy: string | null;
  approvalDate: Date | null;
  approvalExpiryDate: Date | null;
  approvalReference: string | null;
  approvalRequirementBy: string | null;
  approvalValidFor: number | null;
  chairsAction: number | null;
  created: number | null;
  createdAt: Date;
  createdBy: string | null;
  decisionNotificationWorkflow_2: string | null;
  doNotUseApprovalExpiryDate: Date | null;
  doNotUsePiName: string | null;
  doNotUsePreviousStatus: string | null;
  emailComments: string | null;
  enterpriseProject: string | null;
  ethicsPanelView: string | null;
  firstApproved: number | null;
  healthOfSport: string | null;
  id: string;
  institution: string | null;
  itemType: string | null;
  meetingDate: Date | null;
  migrateFlow: string | null;
  modified: number | null;
  modifiedBy: string | null;
  newApplicationRequest: string | null;
  notes: number | null;
  path: string | null;
  principalInvestigator: string | null;
  projectStatus: string | null;
  projectSupervisor: string | null;
  projectTitle: string | null;
  projectType: string | null;
  requiresChairsAction: number | null;
  reSubmission: number | null;
  specialConsideration: string | null;
  testEmailToPrincipleInvestigator: string | null;
  updatedAt: Date;
};
